<?php
	$categories = $block->getStoreCategories(true, false, true);
	$categoryHelper = $block->getCategoryHelper();
?>
<?php if(count($categories)>0):?>
	<?php if($this->helper('WebePower\Sitemap\Helper\Data')->isCategoryProduct()):?>
		<h2 class="sitemap-title"><?php echo __('Catalog');?></h2>
		<ul id="category-product-sitemap" class="sitemap-list">
		    <?php foreach ($categories as $category): if (!$category->getIsActive()) continue;?>
		        <li>
		        	<a href="<?php echo $categoryHelper->getCategoryUrl($category) ?>"><?php echo $category->getName() ?></a>
		        	<?php $block->getSubCatsHtml($category);?>
		        	<?php if($this->helper('WebePower\Sitemap\Helper\Data')->getConfig('product')==1):?>
			        	<?php $products = $block->getProducts($category);?>
			        	<?php if($products->getSize()>0):?>
			        		<ul class="product-sitemap-list">
				        		<?php foreach ($products as $product):?>
				        			<li>
				        				<a href="<?php echo $product->getProductUrl() ?>"><?php echo $product->getName() ?></a>
				        			</li>
				        		<?php endforeach;?>
			        		</ul>
			        	<?php endif;?>
			        <?php endif;?>
		        </li>
		    <?php endforeach; ?>
		</ul>
		<script type="text/javascript">
			require( [ 'jquery' ], function( $ ) {
				$('.product-sitemap-list').each(function(){
					if($(this).prev('ul').length>0) $(this).prev('ul').find('ul:last').replaceWith($(this));
				});
		    });
		</script>
	<?php else:?>
		<h2 class="sitemap-title"><?php echo __('Categories');?></h2>
		<ul id="category-sitemap" class="sitemap-list">
		    <?php foreach ($categories as $category): if (!$category->getIsActive()) continue;?>
		        <li>
		        	<a href="<?php echo $categoryHelper->getCategoryUrl($category) ?>"><?php echo $category->getName() ?></a>
		        	<?php $block->getSubCatsHtml($category);?>
		        </li>
		    <?php endforeach; ?>
		</ul>
		<script type="text/javascript">
			// require the require function
			requirejs( 
				['require', 'jquery', 'https://unpkg.com/masonry-layout@4.1/dist/masonry.pkgd.min.js' ], function( require, $, Masonry )
			  	{
			    	// require jquery-bridget, it's included in masonry.pkgd.js
				    require( [ 'jquery-bridget/jquery-bridget' ], function( jQueryBridget )
				    {
				      	// make Masonry a jQuery plugin
				      	jQueryBridget( 'masonry', Masonry, $ );
				      	$('#category-sitemap').masonry({ columnWidth: 0, transitionDuration: 500 });
			    	});
				}
			);
		</script>
	<?php endif;?>
<?php endif;?>